logging:
    level:
        org:
            atmosphere: warn
server:
    port: ${PORT:48143}
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: adminPass
        url: jdbc:postgresql://localhost:5432/springlearn
        username: root

    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate.hibernate.format_sql: true
            hibernate.hbm2ddl.auto: create-drop
        open-in-view: false

    sql:
        init:
            mode: always
vaadin:
    allowed-packages: com.vaadin,org.vaadin,com.kish.learn.application
    launch-browser: true


javers:
    sqlSchema:
    sqlSchemaManagementEnabled: true
    sqlGlobalIdCacheDisabled: false
    objectAccessHook: org.javers.hibernate.integration.HibernateUnproxyObjectAccessHook
    sqlGlobalIdTableName: jv_global_id
    sqlCommitTableName: jv_commit
    sqlSnapshotTableName: jv_snapshot
    sqlCommitPropertyTableName: jv_commit_property

    mappingStyle: FIELD
    algorithm: SIMPLE
    commitIdGenerator: synchronized_sequence
    prettyPrint: true
    typeSafeValues: false
    initialChanges: true
    terminalChanges: true
    packagesToScan:
    auditableAspectEnabled: true
    springDataAuditableRepositoryAspectEnabled: true
    usePrimitiveDefaults: true
    prettyPrintDateFormats:
        localDateTime: 'dd MMM yyyy, HH:mm:ss'
        zonedDateTime: 'dd MMM yyyy, HH:mm:ssZ'
        localDate: 'dd MMM yyyy'
        localTime: 'HH:mm:ss'